POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video Caua - node",
    "description": "Esse e o primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###
GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/cb5675f9-c18c-402c-a6f7-7b953d9eca9a
Content-Type: application/json

{
    "title": "Video 02 - node",
    "description": "Esse e o segundo video",
    "duration": 120
}

###

DELETE http://localhost:3333/videos/5e60fc7a-b408-4207-bd2d-874861be1257