POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse e o primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###
GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/e9937acf-787d-4ce5-8ab4-640534966ae4
Content-Type: application/json

{
    "title": "Video 02 - node",
    "description": "Esse e o segundo video",
    "duration": 120
}

###

DELETE http://localhost:3333/videos/2d384e47-bd38-434b-8619-4f620ba80a58